### ISSUE TITLE
Accessing bxslider's slider object inside its “onSliderLoad” callback returns undefined

### ISSUE THREAD

**Issue by smohadjer** [stevenwanderski/bxslider-4#475]
Accessing slider variable inside onSliderLoad returns undefined, unless the code is put in a setTimeout. Any idea why?

```
$(window).on('load', function() {
    var slider = $('.bxslider').bxSlider({
        onSliderLoad: function() {
            console.log(slider); //returns undefined

            setTimeout(function() {
                console.log(slider); //returns slider object
            }, 0);
        }
    });
});
```

**Comment by Tidal-Wave** [comment]
Fixed in 4.2.2

**Comment by webivation** [comment]
This is fixed?  Is their any reference or documentation for it?

**Comment by lautit** [comment]
Also interested in any kind of documentation on the new approach of the callback API, trying to decipher on my own hasn't  cleared anything up yet.

**Comment by mikerocker11** [comment]
This is issue is not solved even in the BxSlider v4.2.5

**Comment by peterzicht** [comment]
For ppl still looking for an answer (as it doesn't seem to be solved). Please refer to this codepen: https://codepen.io/eniosan/pen/XJxMNL.

Here you will find a solution where the slideCount is appended to the pager.

**Comment by jeffabruce** [comment]
I know a couple ppl have said it isn't solved, but I think it is. I just don't think it is properly documented. The OP is asking for the _bxSlider_ object, not a DOM element. Presumably this is so that you can call bxSlider methods like "redrawSlider()". Some ppl seem to have that confused.

Technical Explanation: The key is to understanding how the callback is actually called. It is currently being called using the JS "call" method with the bxSlider object as the "this" parameter. So, simply refer to "this" in the callback to access the slider object.

How to Use:
```
$('.bxslider').bxSlider(
{
	onSliderLoad:function( iIndex )
	{
		// "this" refers to the bxSlider object
		this.redrawSlider();
	}
} );
```
